# Generated by Django 3.2.8 on 2021-11-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211111_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Client'), (2, 'Temp_worker'), (3, 'Admin'), (4, 'Accountant')], null=True),
        ),
    ]
