# Generated by Django 3.2.8 on 2021-11-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200)),
                ('order_date', models.DateTimeField()),
                ('order_created', models.DateTimeField(auto_now_add=True)),
                ('emp_count', models.IntegerField()),
                ('emp_qualification', models.TextField()),
                ('order_task', models.TextField()),
                ('task_duration_hours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_status', models.CharField(max_length=200)),
                ('order_comments', models.JSONField()),
                ('order_emp', models.JSONField()),
                ('order_confirm', models.BooleanField()),
                ('order_payment', models.FileField(upload_to='')),
                ('payment_confirm', models.BooleanField()),
            ],
        ),
    ]
